packFormat = "packwiz:1.1.0"
name = "BitsAndBots Pack"
author = "VeryNotJared"
version = "1.0.0"
index = "index.toml"

[versions]
minecraft = "1.20.1"
forge = "47.4.0"

[options]
description = "A custom Forge modpack for BitsAndBots with mods for adventure, building, exploration, and fun."
